# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Deepak Karki
tagline:             'Just another developer'
description:         'A software developer with a passion for systems and physical computing'
url:                 http://deepakkarki.github.io
baseurl:             '/blog'
paginate:            8

#destination
destination:         ../deepakkarki.github.io/blog

# About/contact
author:
  name:              Deepak Karki
  email:             deepak6k@gmail.com

# Custom vars
version:             1.0.0
github:
  repo: 'http://github.com/deepakkarki'
# Global configs
excerpt_separator: <!--more-->
